# Generated by Django 4.0.2 on 2022-03-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
    ]
