# Generated by Django 4.0.2 on 2022-03-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_aboutus_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='user',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='name',
            field=models.CharField(default=2, max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
