# Generated by Django 3.1.4 on 2021-12-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20211217_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['name'], 'verbose_name': 'курсы', 'verbose_name_plural': 'курс'},
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
