# Generated by Django 4.0.2 on 2022-03-01 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_name', to='course.courses'),
        ),
    ]
