# Generated by Django 4.0.2 on 2022-03-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_lessons_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
    ]
