# Generated by Django 4.0.2 on 2022-03-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_courses_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='is_publicated',
        ),
    ]
