# Generated by Django 4.0.2 on 2022-03-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_lessons_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='task',
            field=models.URLField(null=True, verbose_name='ссылка к заданию'),
        ),
    ]
