# Generated by Django 4.0.2 on 2022-03-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_lessons_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('speciality', models.CharField(max_length=20, verbose_name='Специалность')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Возраст')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.AlterField(
            model_name='courses',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='modul',
            field=models.IntegerField(default=0, verbose_name='модуль'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='term',
            field=models.IntegerField(default=0, verbose_name='срок(в месяцах)'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='time',
            field=models.IntegerField(default=0, verbose_name='длительность одного урока'),
        ),
        migrations.AddField(
            model_name='courses',
            name='teacher',
            field=models.ManyToManyField(related_name='course_teachers', to='course.Teachers', verbose_name='преподаватель'),
        ),
    ]
