# Generated by Django 4.0.2 on 2022-03-08 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_teachers_alter_courses_draft_alter_courses_modul_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'звезда рейтинга',
                'verbose_name_plural': 'звезда рейтинга',
                'ordering': ['-value'],
            },
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'ordering': ['name'], 'verbose_name': 'ментор', 'verbose_name_plural': 'менторы'},
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courses', verbose_name='курс')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.ratingstar', verbose_name='звезда')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
    ]
