# Generated by Django 4.0.2 on 2022-03-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254)),
                ('addres', models.TextField(max_length=5000, verbose_name='Адрес')),
                ('telephone', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Обратный связь',
                'verbose_name_plural': 'Обратные связи',
            },
        ),
    ]
