# Generated by Django 4.0.2 on 2022-03-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='password',
        ),
        migrations.AddField(
            model_name='contacts',
            name='description',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='telephone',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
    ]
