# Generated by Django 4.0.2 on 2022-03-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contacts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='addres',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание'),
        ),
    ]
